"""AUTO-GENERATED by scripts/generate_mcp.py — do not edit by hand.

Regenerate with: python scripts/generate_mcp.py
"""
# ruff: noqa: E501

from __future__ import annotations

import os
import sys
from typing import Annotated, Literal, Optional

from fastmcp import FastMCP
from pydantic import Field

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

try:  # run from the repo root (python mcp_server/server.py)
    from mcp_server.tool_surface import (
        COMMON_ANNOTATIONS,
        OUTPUT_SCHEMA,
        SERVER_NAME,
        SERVER_VERSION,
        call_tool,
    )
except ImportError:  # installed as a top-level module (pip install intangible-valuation-mcp)
    from tool_surface import (  # type: ignore[no-redef]
        COMMON_ANNOTATIONS,
        OUTPUT_SCHEMA,
        SERVER_NAME,
        SERVER_VERSION,
        call_tool,
    )

mcp = FastMCP(SERVER_NAME, version=SERVER_VERSION)

@mcp.tool(
    name='valuation_time_value',
    title='Time Value of Money',
    description='Time value of money: discount or compound a single sum, value level and growing annuities and perpetuities, and compute a terminal value by Gordon growth or exit multiple. Method selects the formula. Use to move cash flows through time or to value a terminal value in a DCF; combine with a rate from valuation_discount_rate. For uneven multi-period cash flows use valuation_income_methods; for rate construction use valuation_discount_rate. Parameters apply per method: present_value needs future_value + discount_rate + periods; future_value needs present_value + discount_rate + periods; annuity_pv needs payment + discount_rate + periods; perpetuity_pv needs payment + discount_rate; growing_annuity_pv needs payment + discount_rate + growth_rate + periods; terminal_value_gordon_growth needs final_year_cashflow + perpetual_growth_rate + discount_rate; terminal_value_exit_multiple needs final_year_cashflow + exit_multiple. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'time-value', 'dcf', 'terminal-value'},
)
def valuation_time_value(
    method: Annotated[Literal['present_value', 'future_value', 'annuity_pv', 'perpetuity_pv', 'growing_annuity_pv', 'terminal_value_gordon_growth', 'terminal_value_exit_multiple'], Field(description='Formula to apply. Options: present_value = PV = FV / (1 + r)^n.; future_value = FV = PV * (1 + r)^n.; annuity_pv = PV = PMT * [1 - (1 + r)^-n] / r.; perpetuity_pv = PV = PMT / r.; growing_annuity_pv = PV of a constant-growth annuity.; terminal_value_gordon_growth = TV = FCF * (1 + g) / (r - g).; terminal_value_exit_multiple = TV = FCF * exit multiple.')],
    future_value: Annotated[Optional[float], Field(description='Future cash amount to discount, in currency units.')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    periods: Annotated[Optional[int], Field(description='Number of periods n (non-negative).')] = None,
    present_value: Annotated[Optional[float], Field(description='Present amount to compound, in currency units.')] = None,
    payment: Annotated[Optional[float], Field(description='Recurring payment per period, in currency units.')] = None,
    growth_rate: Annotated[Optional[float], Field(description='Per-period growth rate as a decimal (0.03 = 3%).')] = None,
    final_year_cashflow: Annotated[Optional[float], Field(description='Final-year projected cash flow (FCF), in currency units.')] = None,
    perpetual_growth_rate: Annotated[Optional[float], Field(description='Perpetual growth rate g as a decimal; must be below discount_rate for Gordon growth.')] = None,
    exit_multiple: Annotated[Optional[float], Field(description='Exit multiple applied to the final-year cash flow (e.g. 8.0 for 8x).')] = None,
) -> dict:
    """Time value of money: discount or compound a single sum, value level and growing annuities and perpetuities, and compute a terminal value by Gordon growth or exit multiple."""
    return call_tool('valuation_time_value', {'method': method, 'future_value': future_value, 'discount_rate': discount_rate, 'periods': periods, 'present_value': present_value, 'payment': payment, 'growth_rate': growth_rate, 'final_year_cashflow': final_year_cashflow, 'perpetual_growth_rate': perpetual_growth_rate, 'exit_multiple': exit_multiple})

@mcp.tool(
    name='valuation_discount_rate',
    title='Discount & Capitalization Rates',
    description='Construct discount and capitalization rates: build-up, CAPM, WACC, tax-amortization benefit, control premium, Finnerty DLOM, and currency/country-risk adjustment. Method selects the formula. Use to derive the rate that feeds every income-based method; build_up and capm estimate cost of equity, wacc blends debt and equity. For a cross-border rate with currency and country premia use method currency_adjusted; for the cash flows the rate discounts use valuation_time_value. Parameters apply per method: build_up needs risk_free_rate + equity_risk_premium (optional: size_premium, industry_risk_premium, specific_risk_premium); capm needs risk_free_rate + beta + market_return; wacc needs equity_value + debt_value + cost_of_equity + cost_of_debt + tax_rate; tax_amortization_benefit needs discount_rate + useful_life + tax_rate + asset_value; control_premium needs minority_price + control_price; dlom_finnerty needs restricted_period + volatility + risk_free_rate; currency_adjusted needs base_rate (optional: currency_risk_premium, country_risk_premium). Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'discount-rate', 'capm', 'wacc', 'dlom'},
)
def valuation_discount_rate(
    method: Annotated[Literal['build_up', 'capm', 'wacc', 'tax_amortization_benefit', 'control_premium', 'dlom_finnerty', 'currency_adjusted'], Field(description='Formula to apply. Options: build_up = r = Rf + ERP + size + industry + specific premiums.; capm = r = Rf + beta * (Rm - Rf).; wacc = WACC = (E/V) Re + (D/V) Rd (1 - Tc).; tax_amortization_benefit = PV of the tax shield from amortizing the asset.; control_premium = (Control price - minority price) / minority price.; dlom_finnerty = Finnerty average-strike put option DLOM.; currency_adjusted = r = base rate + currency premium + country premium.')],
    risk_free_rate: Annotated[Optional[float], Field(description='Risk-free rate as a decimal (0.04 = 4%).')] = None,
    equity_risk_premium: Annotated[Optional[float], Field(description='Equity risk premium as a decimal (0.06 = 6%).')] = None,
    size_premium: Annotated[Optional[float], Field(description='Small-size premium as a decimal.')] = None,
    industry_risk_premium: Annotated[Optional[float], Field(description='Industry risk premium as a decimal.')] = None,
    specific_risk_premium: Annotated[Optional[float], Field(description='Company-specific risk premium as a decimal.')] = None,
    beta: Annotated[Optional[float], Field(description='Systematic risk beta (market = 1.0).')] = None,
    market_return: Annotated[Optional[float], Field(description='Expected market return as a decimal (0.10 = 10%).')] = None,
    equity_value: Annotated[Optional[float], Field(description='Market value of equity E, in currency units.')] = None,
    debt_value: Annotated[Optional[float], Field(description='Market value of debt D, in currency units.')] = None,
    cost_of_equity: Annotated[Optional[float], Field(description='Cost of equity Re as a decimal.')] = None,
    cost_of_debt: Annotated[Optional[float], Field(description='Pre-tax cost of debt Rd as a decimal.')] = None,
    tax_rate: Annotated[Optional[float], Field(description='Marginal tax rate as a decimal (0.25 = 25%).')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    useful_life: Annotated[Optional[int], Field(description='Useful life in years n.')] = None,
    asset_value: Annotated[Optional[float], Field(description='Asset value the tax amortization benefit is computed on, in currency units.')] = None,
    minority_price: Annotated[Optional[float], Field(description='Minority (pre-control) share price or value, in currency units.')] = None,
    control_price: Annotated[Optional[float], Field(description='Controlling-interest share price or value, in currency units.')] = None,
    restricted_period: Annotated[Optional[float], Field(description='Restricted / marketability period in years t.')] = None,
    volatility: Annotated[Optional[float], Field(description='Annualized volatility sigma as a decimal (0.30 = 30%).')] = None,
    base_rate: Annotated[Optional[float], Field(description='Base discount rate before currency/country adjustment, as a decimal.')] = None,
    currency_risk_premium: Annotated[Optional[float], Field(description='Currency risk premium as a decimal.')] = None,
    country_risk_premium: Annotated[Optional[float], Field(description='Country risk premium as a decimal.')] = None,
) -> dict:
    """Construct discount and capitalization rates: build-up, CAPM, WACC, tax-amortization benefit, control premium, Finnerty DLOM, and currency/country-risk adjustment."""
    return call_tool('valuation_discount_rate', {'method': method, 'risk_free_rate': risk_free_rate, 'equity_risk_premium': equity_risk_premium, 'size_premium': size_premium, 'industry_risk_premium': industry_risk_premium, 'specific_risk_premium': specific_risk_premium, 'beta': beta, 'market_return': market_return, 'equity_value': equity_value, 'debt_value': debt_value, 'cost_of_equity': cost_of_equity, 'cost_of_debt': cost_of_debt, 'tax_rate': tax_rate, 'discount_rate': discount_rate, 'useful_life': useful_life, 'asset_value': asset_value, 'minority_price': minority_price, 'control_price': control_price, 'restricted_period': restricted_period, 'volatility': volatility, 'base_rate': base_rate, 'currency_risk_premium': currency_risk_premium, 'country_risk_premium': country_risk_premium})

@mcp.tool(
    name='valuation_cost_approach',
    title='Cost Approach',
    description='Cost approach: depreciated reproduction cost from a cost breakdown and depreciated replacement cost with equivalent utility, both reduced by obsolescence. Method selects the formula. Use when no income or market evidence exists, or to corroborate income and market indications for internally developed intangibles. For income-based indications use valuation_income_methods; for market evidence use valuation_market_approach. Parameters apply per method: reproduction_cost needs development_costs (optional: obsolescence_factors); replacement_cost needs current_cost (optional: obsolescence_factors). obsolescence_factors values are decimals that are summed and applied to the cost base; omit them for no obsolescence. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'cost-approach', 'reproduction', 'replacement'},
)
def valuation_cost_approach(
    method: Annotated[Literal['reproduction_cost', 'replacement_cost'], Field(description='Formula to apply. Options: reproduction_cost = Sum of cost categories less total obsolescence.; replacement_cost = Current cost of equivalent utility less obsolescence.')],
    development_costs: Annotated[Optional[dict], Field(description='Cost breakdown by category, e.g. {"r_and_d": 1000000, "testing": 250000}, in currency units.')] = None,
    obsolescence_factors: Annotated[Optional[dict], Field(description='Obsolescence factors, e.g. {"functional": 0.10, "technological": 0.15, "economic": 0.05}.')] = None,
    current_cost: Annotated[Optional[float], Field(description='Current cost to replace the asset with equivalent utility, in currency units.')] = None,
) -> dict:
    """Cost approach: depreciated reproduction cost from a cost breakdown and depreciated replacement cost with equivalent utility, both reduced by obsolescence."""
    return call_tool('valuation_cost_approach', {'method': method, 'development_costs': development_costs, 'obsolescence_factors': obsolescence_factors, 'current_cost': current_cost})

@mcp.tool(
    name='valuation_market_approach',
    title='Market Approach',
    description='Market approach: value from comparable transaction revenue multiples or capitalize a royalty stream into a perpetuity value. Method selects the formula. Use when reliable comparable transactions or royalty rates exist for the subject asset. For income-based excess earnings use valuation_income_methods; for royalty-rate selection and adjustment use valuation_royalty_analysis. Parameters apply per method: comparable_transactions needs comparables + subject_revenue (optional: adjustments); royalty_capitalization needs revenue + royalty_rate + discount_rate. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'market-approach', 'comparables', 'royalty-capitalization'},
)
def valuation_market_approach(
    method: Annotated[Literal['comparable_transactions', 'royalty_capitalization'], Field(description='Formula to apply. Options: comparable_transactions = Subject revenue times the median comparable multiple.; royalty_capitalization = Value = (revenue * royalty rate) / discount rate.')],
    comparables: Annotated[Optional[list[dict]], Field(description='Comparable transactions, each {revenue, multiple}.')] = None,
    subject_revenue: Annotated[Optional[float], Field(description='Subject company revenue, in currency units.')] = None,
    adjustments: Annotated[Optional[dict], Field(description='Optional multiplicative adjustments, e.g. {"size": 0.9, "growth": 1.1}.')] = None,
    revenue: Annotated[Optional[float], Field(description='Annual revenue attributable to the asset, in currency units.')] = None,
    royalty_rate: Annotated[Optional[float], Field(description='Royalty rate as a decimal (0.05 = 5% of revenue).')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
) -> dict:
    """Market approach: value from comparable transaction revenue multiples or capitalize a royalty stream into a perpetuity value."""
    return call_tool('valuation_market_approach', {'method': method, 'comparables': comparables, 'subject_revenue': subject_revenue, 'adjustments': adjustments, 'revenue': revenue, 'royalty_rate': royalty_rate, 'discount_rate': discount_rate})

@mcp.tool(
    name='valuation_income_methods',
    title='Income Methods',
    description='Income approach: relief from royalty, multi-period and single-period excess earnings, incremental cash flow, and contributory asset charges. Method selects the formula. Use for the primary valuation of identifiable intangibles where cash flows can be projected; MPEE for customer-related and technology assets, RFR for IP with observable royalty rates. For royalty-rate inputs use valuation_royalty_analysis; for cost or market indications use valuation_cost_approach and valuation_market_approach. Parameters apply per method: relief_from_royalty needs revenue_projections + royalty_rate + discount_rate + tax_rate + useful_life (optional: tab_enabled); mpeem needs cash_flow_projections + contributory_asset_charges + discount_rate + tax_rate (optional: tab_enabled); single_period_excess_earnings needs normalized_earnings + contributory_asset_charges + capitalization_rate; incremental_cashflow needs cash_flows_with + cash_flows_without + discount_rate; contributory_asset_charges needs assets. cash_flow_projections and contributory_asset_charges must be period-aligned; cash_flows_with and cash_flows_without must be equal length. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'income-approach', 'relief-from-royalty', 'mpeem', 'excess-earnings'},
)
def valuation_income_methods(
    method: Annotated[Literal['relief_from_royalty', 'mpeem', 'single_period_excess_earnings', 'incremental_cashflow', 'contributory_asset_charges'], Field(description='Formula to apply. Options: relief_from_royalty = PV of after-tax royalties avoided by ownership.; mpeem = PV of excess earnings after contributory asset charges.; single_period_excess_earnings = Capitalize one period of excess earnings.; incremental_cashflow = PV of cash flows with the asset minus without it.; contributory_asset_charges = Total contributory asset charges.')],
    revenue_projections: Annotated[Optional[list[float]], Field(description='Projected revenue per period t=1..n, in currency units.')] = None,
    royalty_rate: Annotated[Optional[float], Field(description='Royalty rate as a decimal (0.05 = 5% of revenue).')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    tax_rate: Annotated[Optional[float], Field(description='Marginal tax rate as a decimal (0.25 = 25%).')] = None,
    useful_life: Annotated[Optional[int], Field(description='Useful life in years n.')] = None,
    tab_enabled: Annotated[Optional[bool], Field(description='Whether to include the tax amortization benefit in the result.')] = None,
    cash_flow_projections: Annotated[Optional[list[float]], Field(description='Projected after-tax cash flows per period t=1..n, in currency units.')] = None,
    contributory_asset_charges: Annotated[Optional[list[float]], Field(description='Contributory asset charge per period t=1..n, in currency units.')] = None,
    normalized_earnings: Annotated[Optional[float], Field(description='Single-period normalized earnings, in currency units.')] = None,
    capitalization_rate: Annotated[Optional[float], Field(description='Capitalization rate as a decimal (0.15 = 15%).')] = None,
    cash_flows_with: Annotated[Optional[list[float]], Field(description='Cash flows per period with the asset, in currency units.')] = None,
    cash_flows_without: Annotated[Optional[list[float]], Field(description='Cash flows per period without the asset, in currency units.')] = None,
    assets: Annotated[Optional[list[dict]], Field(description='Contributory assets, each {value, return_rate}.')] = None,
) -> dict:
    """Income approach: relief from royalty, multi-period and single-period excess earnings, incremental cash flow, and contributory asset charges."""
    return call_tool('valuation_income_methods', {'method': method, 'revenue_projections': revenue_projections, 'royalty_rate': royalty_rate, 'discount_rate': discount_rate, 'tax_rate': tax_rate, 'useful_life': useful_life, 'tab_enabled': tab_enabled, 'cash_flow_projections': cash_flow_projections, 'contributory_asset_charges': contributory_asset_charges, 'normalized_earnings': normalized_earnings, 'capitalization_rate': capitalization_rate, 'cash_flows_with': cash_flows_with, 'cash_flows_without': cash_flows_without, 'assets': assets})

@mcp.tool(
    name='valuation_ip',
    title='Intellectual Property',
    description='Intellectual property: risk-adjusted patent value, trademark/brand value, copyright income value, and trade-secret value under secrecy risk. Method selects the formula. Use to value a specific IP right; patent weights projected cash flows by probability of success, trademark uses brand strength to set the royalty. For technology, software, data, and platform assets use valuation_technology; for customer and workforce assets use valuation_customer and valuation_human_capital. Parameters apply per method: patent needs remaining_life + cash_flow_projections + probability_of_success + discount_rate (optional: comparable_license_rates); trademark needs revenue + profit_margin + brand_strength_index + discount_rate + useful_life (optional: brand_method); copyright needs projected_revenue + useful_life + discount_rate + royalty_rate; trade_secret needs development_cost + economic_life + competitive_advantage_period + discount_rate + secrecy_probability. cash_flow_projections for patent run over remaining_life. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'ip', 'patent', 'trademark', 'copyright', 'trade-secret'},
)
def valuation_ip(
    method: Annotated[Literal['patent', 'trademark', 'copyright', 'trade_secret'], Field(description="Formula to apply. Options: patent = Risk-adjusted DCF over the patent's remaining life.; trademark = Brand value by relief-from-royalty or excess earnings.; copyright = PV of expected copyright royalty income.; trade_secret = Value under secrecy risk over the economic life.")],
    remaining_life: Annotated[Optional[int], Field(description='Remaining legal/economic life of the patent in years.')] = None,
    cash_flow_projections: Annotated[Optional[list[float]], Field(description='Projected after-tax cash flows per period t=1..n, in currency units.')] = None,
    probability_of_success: Annotated[Optional[float], Field(description='Probability of technical and commercial success, in [0,1].')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    comparable_license_rates: Annotated[Optional[list[float]], Field(description='Comparable license royalty rates as decimals.')] = None,
    revenue: Annotated[Optional[float], Field(description='Annual revenue attributable to the asset, in currency units.')] = None,
    profit_margin: Annotated[Optional[float], Field(description='Profit margin as a decimal (0.20 = 20%).')] = None,
    brand_strength_index: Annotated[Optional[float], Field(description='Brand strength index on a 0-100 scale (75 = strong).')] = None,
    useful_life: Annotated[Optional[int], Field(description='Useful life in years n.')] = None,
    brand_method: Annotated[Optional[Literal['relief_from_royalty', 'excess_earnings']], Field(description='Trademark method: relief_from_royalty adjusts the royalty rate by brand strength; excess_earnings capitalizes excess earnings.')] = None,
    projected_revenue: Annotated[Optional[float], Field(description='Projected annual revenue subject to the copyright royalty, in currency units.')] = None,
    royalty_rate: Annotated[Optional[float], Field(description='Royalty rate as a decimal (0.05 = 5% of revenue).')] = None,
    development_cost: Annotated[Optional[float], Field(description='Development or acquisition cost, in currency units.')] = None,
    economic_life: Annotated[Optional[int], Field(description='Economic life in years.')] = None,
    competitive_advantage_period: Annotated[Optional[int], Field(description='Years the competitive advantage is expected to persist.')] = None,
    secrecy_probability: Annotated[Optional[float], Field(description='Probability the trade secret remains secret, in [0,1].')] = None,
) -> dict:
    """Intellectual property: risk-adjusted patent value, trademark/brand value, copyright income value, and trade-secret value under secrecy risk."""
    return call_tool('valuation_ip', {'method': method, 'remaining_life': remaining_life, 'cash_flow_projections': cash_flow_projections, 'probability_of_success': probability_of_success, 'discount_rate': discount_rate, 'comparable_license_rates': comparable_license_rates, 'revenue': revenue, 'profit_margin': profit_margin, 'brand_strength_index': brand_strength_index, 'useful_life': useful_life, 'brand_method': brand_method, 'projected_revenue': projected_revenue, 'royalty_rate': royalty_rate, 'development_cost': development_cost, 'economic_life': economic_life, 'competitive_advantage_period': competitive_advantage_period, 'secrecy_probability': secrecy_probability})

@mcp.tool(
    name='valuation_technology',
    title='Technology Assets',
    description='Technology assets: developed technology under life-cycle risk, software under cost and income, data assets with a quality adjustment, and platforms with network effects. Method selects the formula. Use for developed technology, software, data, and platform intangibles; developed_technology and software blend cost and income evidence. For patents, trademarks, copyrights, and trade secrets use valuation_ip; for customer relationships use valuation_customer. Parameters apply per method: developed_technology needs rd_costs + life_cycle_stage + competitive_advantage + discount_rate + cash_flow_projections; software needs development_cost + maintenance_cost + user_base + revenue_model + useful_life + discount_rate; data_asset needs acquisition_cost + quality_score + revenue_contribution + useful_life + discount_rate; platform needs network_size + network_effects_coefficient + revenue_per_user + growth_rate + discount_rate. cash_flow_projections for developed_technology run over the remaining useful life. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'technology', 'software', 'data', 'platform'},
)
def valuation_technology(
    method: Annotated[Literal['developed_technology', 'software', 'data_asset', 'platform'], Field(description='Formula to apply. Options: developed_technology = Cost and income value adjusted for life-cycle stage.; software = Software value from development, maintenance, and revenue.; data_asset = Quality-adjusted revenue contribution plus acquisition cost.; platform = Network-effect revenue grown and discounted.')],
    rd_costs: Annotated[Optional[float], Field(description='Cumulative research and development costs, in currency units.')] = None,
    life_cycle_stage: Annotated[Optional[str], Field(description='Life-cycle stage, e.g. "growth", "mature", "decline".')] = None,
    competitive_advantage: Annotated[Optional[int], Field(description='Years of competitive advantage.')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    cash_flow_projections: Annotated[Optional[list[float]], Field(description='Projected after-tax cash flows per period t=1..n, in currency units.')] = None,
    development_cost: Annotated[Optional[float], Field(description='Development or acquisition cost, in currency units.')] = None,
    maintenance_cost: Annotated[Optional[float], Field(description='Annual maintenance cost, in currency units.')] = None,
    user_base: Annotated[Optional[int], Field(description='Number of users.')] = None,
    revenue_model: Annotated[Optional[dict], Field(description='Revenue model, e.g. {"subscription_price": 20, "paying_users": 10000}.')] = None,
    useful_life: Annotated[Optional[int], Field(description='Useful life in years n.')] = None,
    acquisition_cost: Annotated[Optional[float], Field(description='Cost to acquire the data, in currency units.')] = None,
    quality_score: Annotated[Optional[float], Field(description='Data quality score, in [0,1].')] = None,
    revenue_contribution: Annotated[Optional[float], Field(description='Annual revenue contribution, in currency units.')] = None,
    network_size: Annotated[Optional[int], Field(description='Number of network participants.')] = None,
    network_effects_coefficient: Annotated[Optional[float], Field(description='Network-effects coefficient scaling revenue with network size.')] = None,
    revenue_per_user: Annotated[Optional[float], Field(description='Revenue per user, in currency units.')] = None,
    growth_rate: Annotated[Optional[float], Field(description='Per-period growth rate as a decimal (0.03 = 3%).')] = None,
) -> dict:
    """Technology assets: developed technology under life-cycle risk, software under cost and income, data assets with a quality adjustment, and platforms with network effects."""
    return call_tool('valuation_technology', {'method': method, 'rd_costs': rd_costs, 'life_cycle_stage': life_cycle_stage, 'competitive_advantage': competitive_advantage, 'discount_rate': discount_rate, 'cash_flow_projections': cash_flow_projections, 'development_cost': development_cost, 'maintenance_cost': maintenance_cost, 'user_base': user_base, 'revenue_model': revenue_model, 'useful_life': useful_life, 'acquisition_cost': acquisition_cost, 'quality_score': quality_score, 'revenue_contribution': revenue_contribution, 'network_size': network_size, 'network_effects_coefficient': network_effects_coefficient, 'revenue_per_user': revenue_per_user, 'growth_rate': growth_rate})

@mcp.tool(
    name='valuation_customer',
    title='Customer-Related Assets',
    description='Customer-related intangibles: customer relationships with attrition, distribution networks by channel profitability, and non-compete agreements on protected profits. Method selects the formula. Use for customer relationships, distribution networks, and non-compete assets; customer_relationships projects multi-period revenue with a retention rate. For the workforce and key-person assets use valuation_human_capital; for technology assets use valuation_technology. Parameters apply per method: customer_relationships needs customer_count + avg_revenue_per_customer + retention_rate + profit_margin + discount_rate + projection_period; distribution_network needs channel_count + revenue_per_channel + channel_margin + useful_life + discount_rate; non_compete needs protected_revenue + profit_margin + term + enforcement_probability + discount_rate. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'customer', 'distribution', 'non-compete'},
)
def valuation_customer(
    method: Annotated[Literal['customer_relationships', 'distribution_network', 'non_compete'], Field(description='Formula to apply. Options: customer_relationships = Multi-period revenue net of attrition, discounted.; distribution_network = Channel revenue times margin over the useful life.; non_compete = Protected profit under an enforcement probability, discounted.')],
    customer_count: Annotated[Optional[int], Field(description='Number of customers.')] = None,
    avg_revenue_per_customer: Annotated[Optional[float], Field(description='Average annual revenue per customer, in currency units.')] = None,
    retention_rate: Annotated[Optional[float], Field(description='Annual customer retention rate, in [0,1].')] = None,
    profit_margin: Annotated[Optional[float], Field(description='Profit margin as a decimal (0.20 = 20%).')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    projection_period: Annotated[Optional[int], Field(description='Projection horizon in years.')] = None,
    channel_count: Annotated[Optional[int], Field(description='Number of distribution channels.')] = None,
    revenue_per_channel: Annotated[Optional[float], Field(description='Annual revenue per channel, in currency units.')] = None,
    channel_margin: Annotated[Optional[float], Field(description='Channel profit margin as a decimal.')] = None,
    useful_life: Annotated[Optional[int], Field(description='Useful life in years n.')] = None,
    protected_revenue: Annotated[Optional[float], Field(description='Annual revenue protected by the non-compete, in currency units.')] = None,
    term: Annotated[Optional[int], Field(description='Non-compete term in years.')] = None,
    enforcement_probability: Annotated[Optional[float], Field(description='Probability the non-compete is enforceable, in [0,1].')] = None,
) -> dict:
    """Customer-related intangibles: customer relationships with attrition, distribution networks by channel profitability, and non-compete agreements on protected profits."""
    return call_tool('valuation_customer', {'method': method, 'customer_count': customer_count, 'avg_revenue_per_customer': avg_revenue_per_customer, 'retention_rate': retention_rate, 'profit_margin': profit_margin, 'discount_rate': discount_rate, 'projection_period': projection_period, 'channel_count': channel_count, 'revenue_per_channel': revenue_per_channel, 'channel_margin': channel_margin, 'useful_life': useful_life, 'protected_revenue': protected_revenue, 'term': term, 'enforcement_probability': enforcement_probability})

@mcp.tool(
    name='valuation_human_capital',
    title='Human Capital',
    description='Human capital: assembled-workforce value by replacement cost and key-person value from revenue contribution and departure risk. Method selects the formula. Use for assembled workforce and key-person intangibles; assembled_workforce nets training and attrition into a replacement cost. For customer-related assets use valuation_customer; for technology assets use valuation_technology. Parameters apply per method: assembled_workforce needs employee_count + avg_replacement_cost + training_cost + productivity_factor + attrition_rate; key_person needs revenue_contribution + replacement_cost + departure_probability + discount_rate. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'human-capital', 'assembled-workforce', 'key-person'},
)
def valuation_human_capital(
    method: Annotated[Literal['assembled_workforce', 'key_person'], Field(description='Formula to apply. Options: assembled_workforce = Replacement cost including training, net of attrition.; key_person = Revenue contribution and replacement cost under departure risk.')],
    employee_count: Annotated[Optional[int], Field(description='Number of employees.')] = None,
    avg_replacement_cost: Annotated[Optional[float], Field(description='Average cost to replace one employee, in currency units.')] = None,
    training_cost: Annotated[Optional[float], Field(description='Training cost per employee, in currency units.')] = None,
    productivity_factor: Annotated[Optional[float], Field(description='Productivity factor on replacement cost (1.0 = parity).')] = None,
    attrition_rate: Annotated[Optional[float], Field(description='Annual attrition rate, in [0,1].')] = None,
    revenue_contribution: Annotated[Optional[float], Field(description='Annual revenue contribution, in currency units.')] = None,
    replacement_cost: Annotated[Optional[float], Field(description='Cost to replace the key person, in currency units.')] = None,
    departure_probability: Annotated[Optional[float], Field(description='Annual probability the key person departs, in [0,1].')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
) -> dict:
    """Human capital: assembled-workforce value by replacement cost and key-person value from revenue contribution and departure risk."""
    return call_tool('valuation_human_capital', {'method': method, 'employee_count': employee_count, 'avg_replacement_cost': avg_replacement_cost, 'training_cost': training_cost, 'productivity_factor': productivity_factor, 'attrition_rate': attrition_rate, 'revenue_contribution': revenue_contribution, 'replacement_cost': replacement_cost, 'departure_probability': departure_probability, 'discount_rate': discount_rate})

@mcp.tool(
    name='valuation_goodwill_ppa',
    title='Goodwill & Purchase Price Allocation',
    description='Goodwill and purchase price allocation: goodwill as the residual, a full PPA waterfall across identified intangibles, and useful-life estimation. Method selects the formula. Use for ASC 805 / IFRS 3 business combinations; purchase_price_allocation allocates consideration to identified intangibles with the remainder to goodwill. For subsequent goodwill and intangible impairment testing use valuation_impairment; for individual intangible fair values feed valuation_ip, valuation_technology or valuation_customer into the allocation. Parameters apply per method: goodwill needs purchase_price + fair_value_net_identifiable_assets; purchase_price_allocation needs purchase_price + tangible_assets_fv + identified_intangibles (optional: liabilities_fv); useful_life needs asset_type (optional: legal_life, economic_factors, obsolescence_rate). identified_intangibles values are summed before goodwill is taken as the residual; liabilities_fv reduces net identifiable assets. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'goodwill', 'ppa', 'asc-805', 'ifrs-3', 'useful-life'},
)
def valuation_goodwill_ppa(
    method: Annotated[Literal['goodwill', 'purchase_price_allocation', 'useful_life'], Field(description='Formula to apply. Options: goodwill = Goodwill = purchase price - fair value of net identifiable assets.; purchase_price_allocation = Allocate consideration across identified intangibles.; useful_life = Estimate economic/legal useful life of an intangible.')],
    purchase_price: Annotated[Optional[float], Field(description='Total consideration / purchase price, in currency units.')] = None,
    fair_value_net_identifiable_assets: Annotated[Optional[float], Field(description='Fair value of net identifiable assets, in currency units.')] = None,
    tangible_assets_fv: Annotated[Optional[float], Field(description='Fair value of tangible assets, in currency units.')] = None,
    identified_intangibles: Annotated[Optional[list[dict]], Field(description='Identified intangibles, each {name, value} or {name, fair_value}.')] = None,
    liabilities_fv: Annotated[Optional[float], Field(description='Fair value of assumed liabilities, in currency units.')] = None,
    asset_type: Annotated[Optional[str], Field(description='Asset type, e.g. "patent", "trademark", "software", "customer_list".')] = None,
    legal_life: Annotated[Optional[float], Field(description='Legal protection period in years (overrides the asset-type default).')] = None,
    economic_factors: Annotated[Optional[dict], Field(description='Economic adjustment factors, e.g. {"market_growth": 0.05, "competition": 0.4, "tech_change": 0.1}.')] = None,
    obsolescence_rate: Annotated[Optional[float], Field(description='Annual obsolescence rate as a decimal.')] = None,
) -> dict:
    """Goodwill and purchase price allocation: goodwill as the residual, a full PPA waterfall across identified intangibles, and useful-life estimation."""
    return call_tool('valuation_goodwill_ppa', {'method': method, 'purchase_price': purchase_price, 'fair_value_net_identifiable_assets': fair_value_net_identifiable_assets, 'tangible_assets_fv': tangible_assets_fv, 'identified_intangibles': identified_intangibles, 'liabilities_fv': liabilities_fv, 'asset_type': asset_type, 'legal_life': legal_life, 'economic_factors': economic_factors, 'obsolescence_rate': obsolescence_rate})

@mcp.tool(
    name='valuation_impairment',
    title='Impairment Testing',
    description="Impairment testing: goodwill impairment and intangible impairment under US GAAP (ASC 350) or IFRS (IAS 36). Method selects the formula. Use for annual or triggering-event impairment testing; goodwill_impairment compares a reporting unit's carrying value with its fair value. To compute the initial goodwill or allocation use valuation_goodwill_ppa; for the underlying asset fair values use the relevant asset-type tool. Parameters apply per method: goodwill_impairment needs carrying_value + fair_value (optional: reporting_unit, standard); intangible_impairment needs carrying_value (optional: fair_value, recoverable_amount, standard). fair_value is required for ASC350; recoverable_amount is required for IAS36. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.",
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'impairment', 'asc-350', 'ias-36', 'goodwill'},
)
def valuation_impairment(
    method: Annotated[Literal['goodwill_impairment', 'intangible_impairment'], Field(description='Formula to apply. Options: goodwill_impairment = Impairment = carrying value - fair value (if positive).; intangible_impairment = Impairment of an intangible under ASC 350 or IAS 36.')],
    carrying_value: Annotated[Optional[float], Field(description='Carrying value of the reporting unit or asset, in currency units.')] = None,
    fair_value: Annotated[Optional[float], Field(description='Fair value of the reporting unit or asset, in currency units.')] = None,
    reporting_unit: Annotated[Optional[str], Field(description='Reporting unit name (goodwill only).')] = None,
    standard: Annotated[Optional[Literal['ASC350', 'IAS36']], Field(description='Accounting standard: ASC350 for US GAAP, IAS36 for IFRS.')] = None,
    recoverable_amount: Annotated[Optional[float], Field(description='Recoverable amount (IAS 36), in currency units.')] = None,
) -> dict:
    """Impairment testing: goodwill impairment and intangible impairment under US GAAP (ASC 350) or IFRS (IAS 36)."""
    return call_tool('valuation_impairment', {'method': method, 'carrying_value': carrying_value, 'fair_value': fair_value, 'reporting_unit': reporting_unit, 'standard': standard, 'recoverable_amount': recoverable_amount})

@mcp.tool(
    name='valuation_royalty_analysis',
    title='Royalty Rate Analysis',
    description='Royalty analysis: benchmark royalty-rate ranges by IP type and industry, adjust a base rate for deal factors, and apply the 25% rule of thumb. Method selects the formula. Use to select and support a royalty rate before a relief-from-royalty or royalty-capitalization valuation. To apply the chosen rate in a valuation use valuation_income_methods (relief_from_royalty) or valuation_market_approach (royalty_capitalization); for transfer-pricing pricing use valuation_compliance. Parameters apply per method: benchmark needs ip_type + industry (optional: comparable_database); adjust needs base_royalty_rate + adjustment_factors; twenty_five_percent_rule needs licensee_expected_profit (optional: profit_attribution_to_ip). adjustment_factors multiply the base rate, so values above 1.0 raise the rate. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'royalty', 'benchmark', '25-percent-rule'},
)
def valuation_royalty_analysis(
    method: Annotated[Literal['benchmark', 'adjust', 'twenty_five_percent_rule'], Field(description='Formula to apply. Options: benchmark = Benchmark royalty-rate range by IP type and industry.; adjust = Adjusted rate = base rate * product of factors.; twenty_five_percent_rule = Royalty = licensee profit * IP attribution * 25%.')],
    ip_type: Annotated[Optional[str], Field(description='Intellectual-property type, e.g. "patent", "trademark", "copyright", "trade_secret".')] = None,
    industry: Annotated[Optional[str], Field(description='Industry, e.g. "software", "pharmaceutical".')] = None,
    comparable_database: Annotated[Optional[list[dict]], Field(description='Optional comparable licenses, each {rate} or {royalty_rate}.')] = None,
    base_royalty_rate: Annotated[Optional[float], Field(description='Base royalty rate before adjustment, as a decimal (0.05 = 5%).')] = None,
    adjustment_factors: Annotated[Optional[dict], Field(description='Multiplicative adjustment factors, e.g. {"profitability": 1.1, "market": 0.9}.')] = None,
    licensee_expected_profit: Annotated[Optional[float], Field(description='Licensee expected profit, in currency units.')] = None,
    profit_attribution_to_ip: Annotated[Optional[float], Field(description='Fraction of profit attributable to the IP, in [0,1].')] = None,
) -> dict:
    """Royalty analysis: benchmark royalty-rate ranges by IP type and industry, adjust a base rate for deal factors, and apply the 25% rule of thumb."""
    return call_tool('valuation_royalty_analysis', {'method': method, 'ip_type': ip_type, 'industry': industry, 'comparable_database': comparable_database, 'base_royalty_rate': base_royalty_rate, 'adjustment_factors': adjustment_factors, 'licensee_expected_profit': licensee_expected_profit, 'profit_attribution_to_ip': profit_attribution_to_ip})

@mcp.tool(
    name='valuation_simulation',
    title='Uncertainty & Sensitivity',
    description='Uncertainty analysis: Monte Carlo valuation, Monte Carlo sensitivity ranking, decision-tree expected values, and one-at-a-time sensitivity analysis. Method selects the formula. Use to quantify and stress the uncertainty around a point valuation; monte_carlo simulates all listed inputs, monte_carlo_sensitivity ranks the drivers. For a single deterministic point value use the relevant valuation tool; sensitivity_analysis varies one parameter of a core function only. Parameters apply per method: monte_carlo needs input_distributions (optional: iterations, seed); monte_carlo_sensitivity needs base_params + distributions (optional: iterations, seed); decision_tree needs tree; sensitivity_analysis needs function_name + parameter_name + parameter_range + fixed_parameters. monte_carlo_sensitivity requires iterations between 1000 and 100000. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.',
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'monte-carlo', 'sensitivity', 'decision-tree', 'uncertainty'},
)
def valuation_simulation(
    method: Annotated[Literal['monte_carlo', 'monte_carlo_sensitivity', 'decision_tree', 'sensitivity_analysis'], Field(description='Formula to apply. Options: monte_carlo = Simulate all listed inputs, sum-based valuation.; monte_carlo_sensitivity = Rank parameters by their impact on the valuation.; decision_tree = Backward induction over a decision tree.; sensitivity_analysis = One-at-a-time sensitivity of a core function.')],
    input_distributions: Annotated[Optional[list[dict]], Field(description='Inputs to simulate, each {name, distribution, params}; distribution is normal (mean, std), uniform (low, high) or triangular (low, high, mode).')] = None,
    iterations: Annotated[Optional[int], Field(description='Simulation iterations; monte_carlo_sensitivity requires 1000-100000.')] = None,
    seed: Annotated[Optional[int], Field(description='Random seed for reproducible simulations.')] = None,
    base_params: Annotated[Optional[dict], Field(description='Base values for all parameters, including those held fixed.')] = None,
    distributions: Annotated[Optional[dict], Field(description='Map of parameter name to {distribution, params} for the simulated inputs.')] = None,
    tree: Annotated[Optional[dict], Field(description='Decision tree {"nodes": [...], "edges": [...]}; node types decision, chance, terminal.')] = None,
    function_name: Annotated[Optional[str], Field(description='Core function to vary, e.g. "present_value", "capm_discount_rate", "wacc".')] = None,
    parameter_name: Annotated[Optional[str], Field(description='Name of the parameter to vary.')] = None,
    parameter_range: Annotated[Optional[list[float]], Field(description='Values to test for the varied parameter.')] = None,
    fixed_parameters: Annotated[Optional[dict], Field(description='Values for all other parameters, held constant.')] = None,
) -> dict:
    """Uncertainty analysis: Monte Carlo valuation, Monte Carlo sensitivity ranking, decision-tree expected values, and one-at-a-time sensitivity analysis."""
    return call_tool('valuation_simulation', {'method': method, 'input_distributions': input_distributions, 'iterations': iterations, 'seed': seed, 'base_params': base_params, 'distributions': distributions, 'tree': tree, 'function_name': function_name, 'parameter_name': parameter_name, 'parameter_range': parameter_range, 'fixed_parameters': fixed_parameters})

@mcp.tool(
    name='valuation_compliance',
    title='Transfer Pricing & Litigation',
    description="Transfer pricing and litigation: the Comparable Uncontrolled Price arm's-length range and patent infringement damages with pre-judgment interest. Method selects the formula. Use for OECD transfer-pricing pricing of intercompany intangibles and for patent infringement damages awards. For royalty-rate benchmarking to set a rate use valuation_royalty_analysis; for the substantive asset valuation use valuation_ip or valuation_income_methods. Parameters apply per method: cup_transfer_price needs controlled_price + uncontrolled_prices; patent_infringement_damages needs lost_profits_or_royalty + infringement_period + discount_rate + prejudgment_interest_rate. Only method is required; every other parameter is method-dependent, so supply just the ones named for the selected method and leave the rest unset. Deterministic and side-effect-free: identical inputs always return an identical value. Supplying an unknown method, or leaving unset a parameter that the chosen method requires, returns an error instead of a value.",
    output_schema=OUTPUT_SCHEMA,
    annotations=COMMON_ANNOTATIONS,
    tags={'transfer-pricing', 'litigation', 'cup', 'damages'},
)
def valuation_compliance(
    method: Annotated[Literal['cup_transfer_price', 'patent_infringement_damages'], Field(description="Formula to apply. Options: cup_transfer_price = Arm's-length range from comparable uncontrolled prices.; patent_infringement_damages = Lost profits or reasonable royalty plus prejudgment interest.")],
    controlled_price: Annotated[Optional[float], Field(description='Intercompany (controlled) price, in currency units.')] = None,
    uncontrolled_prices: Annotated[Optional[list[float]], Field(description='Comparable uncontrolled prices, in currency units.')] = None,
    lost_profits_or_royalty: Annotated[Optional[float], Field(description='Annual lost profits or reasonable royalty, in currency units.')] = None,
    infringement_period: Annotated[Optional[int], Field(description='Infringement period in years.')] = None,
    discount_rate: Annotated[Optional[float], Field(description='Per-period discount rate as a decimal (0.10 = 10%).')] = None,
    prejudgment_interest_rate: Annotated[Optional[float], Field(description='Pre-judgment interest rate as a decimal.')] = None,
) -> dict:
    """Transfer pricing and litigation: the Comparable Uncontrolled Price arm's-length range and patent infringement damages with pre-judgment interest."""
    return call_tool('valuation_compliance', {'method': method, 'controlled_price': controlled_price, 'uncontrolled_prices': uncontrolled_prices, 'lost_profits_or_royalty': lost_profits_or_royalty, 'infringement_period': infringement_period, 'discount_rate': discount_rate, 'prejudgment_interest_rate': prejudgment_interest_rate})

def main() -> None:
    """Run the stdio MCP server."""
    mcp.run()

if __name__ == "__main__":
    main()
